language: node_js
node_js:
  - "11"
  - "10"
  - "9"
  - "8"
sudo: false
cache:
  directories:
    - node_modules
install:
  - npm install -g npm
  - test -d node_modules && npm prune || true
  - npm install 
script:
  - npm test
#branches:
#  except:
#    - /^gh-.*$/
